### ISSUE TITLE
what does "merging" Datasets do?

### ISSUE THREAD

**Issue by marwahaha** [eparsonnet93/ekpmeasure#18]
Is this the "magic" that handles when data comes from multiple places?

**Comment by eparsonnet93** [comment]
Yes. It handles different keeping track of data that may be stored in different folders. For example:

dset1 = analysis.load_Dataset('path1')
dset2 = analysis.load_Dataset('path2')
dset3 = analysis.load_Dataset('path3')

dset = analysis.merge_Datasets((dset1, dset2, dset3))

 and now you only need the final dset to access any of the data in those folders. I typically use it because I organize my data files by date, so it is common that I want to compare across some set of parameters where the data spans multiple days.

**Comment by marwahaha** [comment]
Neat, thanks for the clarification.
